### ISSUE TITLE
Sudhir_Bhagat_IOS

### ISSUE THREAD

**Issue by sudhir-bhagat** [nets-dev/assignment#3]
I am sudhir bhagat. 
I have 6+ experience in ios developer. I have worked on objective C and swift programming languages. I have worked on bluetooth in ios, core location, core graphics during.
[Resume-SudhirBhagat_iOSDeveloper.docx](https://github.com/nets-dev/assignment/files/8561076/Resume-SudhirBhagat_iOSDeveloper.docx)

**Comment by nets-dev** [comment]
Hi @sudhir-bhagat, we'll grant access of our project shortly. Thank you for your patience in advance!

**Comment by nets-dev** [comment]
@sudhir-bhagat We have sent you an invitation to our repository. You may accept the repository and follow the instructions in README.md of the repository to implement the tasks. Have you received the invitation?

**Comment by sudhir-bhagat** [comment]
Yes. I got the invitation.

Thanks.
