### ISSUE TITLE
Shanmugarajeshwaran B - iOS

### ISSUE THREAD

**Issue by ShanmugarajeshwaranBalasubramanian** [nets-dev/assignment#4]
I am Shanmugarajeshwaran B and I have totally 8 years of experience and 5 plus in Banking domain. I have planned to start the assignment by May 6th 2022

**Comment by nets-dev** [comment]
Hi @ShanmugarajeshwaranBalasubramanian , can you confirm if you've received the invitation?

**Comment by ShanmugarajeshwaranBalasubramanian** [comment]
Hi @nets-dev  Yes I have Received Invite
