### ISSUE TITLE
iOS/Chetan Nikam iOS assignment Request

### ISSUE THREAD

**Issue by chetannikam23** [nets-dev/assignment#50]
Hi, my name is Chetan Nikam. I have about 3 years of experience working as an iOS developer and have experience in Swift. You may grant my GitHub account access to the iOS code assignment. I am free this week and will start working on the project as soon as I get the access. Thanks!

**Comment by nets-dev** [comment]
Hi @chetannikam23 , please use your personal GitHub account with some projects for reference.
As a developer, projects speak louder than years of experience or CV.
(Any project in iOS, even tutorial/school projects would be appreciated)

**Comment by chetannikam23** [comment]
[CAE.zip](https://github.com/nets-dev/assignment/files/9880960/CAE.zip)
[coredata.zip](https://github.com/nets-dev/assignment/files/9880963/coredata.zip)
[SolaceInfo.zip](https://github.com/nets-dev/assignment/files/9880964/SolaceInfo.zip)
